### ISSUE TITLE
Visual Studio Community 2015 - no C++11 support

### ISSUE THREAD

**Issue by CsatiZoltan** [arrayfire/arrayfire-project-templates#4]
For the CMake project, everything works well, but CMake reports that

> The compiler C:/Programok/Visual Studio Community 2015/VC/bin/x86_amd64/cl.exe has no C++11 support. Please use a different C++ compiler.

The example project is built successfully and all backends work perfectly. So why doesn't CMake recognise Visual Studio Community as a C++11 compiler?

**Comment by shehzan10** [comment]
Why CMake doesn't recognize it as a C++11 compiler is a question for CMake.
As far as this project goes, VS2015 as a generator should work just fine. We do not require C++11 in the examples.

**Comment by CsatiZoltan** [comment]
Ok, thank you.
