### ISSUE TITLE
DLL template for visual studio template 

### ISSUE THREAD

**Issue by altaybrusan** [arrayfire/arrayfire-project-templates#5]
Do you have any VS C++ template or can you provide one?

**Comment by shehzan10** [comment]
It's already present - https://github.com/arrayfire/arrayfire-project-templates/tree/master/VS2013/ArrayFire-VS2013

**Comment by altaybrusan** [comment]
@shehzan10 is that enough to change the configuration from .exe to dll? I want to call the function from C sharp.

**Comment by shehzan10** [comment]
We do not have something to export DLL. You should be able to modify that project into exporting a DLL. You will also need to manage the DLL import/export from that.

Individual instructions to set up ArrayFire projects can be found [here](http://arrayfire.org/docs/using_on_windows.htm)

**Comment by altaybrusan** [comment]
@shehzan10 That is the way I have gone through.
I mentioned this issue here because I thought that you may also include that too.
This way you can enrich the sample portfolio, specially for beginners.

**Comment by shehzan10** [comment]
You can open a pull request if you wish to contribute that in.
It's not common for third party users to generally create a DLL. So you can see why we never bothered to create it.
