### ISSUE TITLE
templates for bindings ?

### ISSUE THREAD

**Issue by UniqueFool** [arrayfire/arrayfire-project-templates#6]
are there any templates for creating bindings for scripting languages currently not supported by arrayfire ?

For example, something using SWIG

**Comment by shehzan10** [comment]
This is a project for example templates for users to get started with.
I think what you are looking for are Wrappers.
The following are wrappers hosted on ArrayFire's organization
- https://github.com/arrayfire/arrayfire-python
- https://github.com/arrayfire/arrayfire-rust
- https://github.com/arrayfire/arrayfire-dotnet
- https://github.com/arrayfire/arrayfire-js

Python and Rust are the ones that have parity with ArrayFire.

**Comment by shehzan10** [comment]
Here is a full list of wrappers https://github.com/arrayfire/arrayfire#language-wrappers

**Comment by UniqueFool** [comment]
Thank you (both!), I was aware of that, like you say, I am specifically asking for templates for creating new wrappers, i.e. unsupported scripting languages - or using a binding generator like SWIG for doing so

**Comment by shehzan10** [comment]
There are no templates as such. You are better off looking at the python wrapper and replicating that.

**Comment by UniqueFool** [comment]
wouldn't it make more sense to use a bindings generator like SWIG and extend that to support languages that are not supported otherwise, or did you consciously decide not to use a wrapper generator due to performance considerations ?

**Comment by shehzan10** [comment]
Can you open a discussion on arrayfire/arrayfire? We'll get more eyeballs and feedback there.
Also, the purpose of this specific repository is completely tangential to the current discussion.
