### ISSUE TITLE
Update VS2013 template to VS2015

### ISSUE THREAD

**Issue by Haider-BA** [arrayfire/arrayfire-project-templates#8]
Kindly update VS2013 template to use in VS2015 and with the newest release of Arrayfire 3.4.

**Comment by shehzan10** [comment]
For the time being, we do not anticipate adding VS2015 example project to ArrayFire given the following reasons:
- ArrayFire still has a minimum dependency of VS2013, hence to keep in touch with that, we will continue to ship VS2013 project files.
- VS2013 project files can be upgraded to VS2015. However, VS2015 files cannot be downgraded.
- Given that VS2013 can be upgraded, shipping additional VS2015 files is purely overhead.
- CUDA 7.5 does not support VS2015.
- VS2013 is still has a very high usage ratio.

If one or more of these reasons change in the future we might look to add it. So I will leave this issue open.

**Comment by shehzan10** [comment]
This has been added to master.

**Comment by Haider-BA** [comment]
I tried to run HELLOWORD in VS2015 with CUDA8.0, having following errors:

![capture1](https://cloud.githubusercontent.com/assets/10229251/19334789/985759a4-9139-11e6-9deb-132ce4643a84.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10229251/19334811/bb990110-9139-11e6-90b3-cc5438ea3cd4.PNG)
![capture3](https://cloud.githubusercontent.com/assets/10229251/19334813/c0c9e2a8-9139-11e6-8959-76c20e1a5591.PNG)
![capture4](https://cloud.githubusercontent.com/assets/10229251/19334814/c4c6a49a-9139-11e6-899b-beb4107eaacf.PNG)

These libraries are installed with CUDA installation, as I know.

**Comment by shehzan10** [comment]
ArrayFire v3.4.0 is still on CUDA 7.5. We completed this release with the v3.4.1 release in mind which will happen on Monday, Oct 17 2016.
